### pandas Pathon Data Analysis Library

#### 数据分析三剑客  pandas numpy matplotlib

Series 是一种类似一维数组的对象， 
- index : 相关数据索引标签
- values : 一组数据

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
from pandas import Series, DataFrame

In [15]:
s1 = Series([1, 2, 3, 4])

In [16]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [17]:
s1.index  # 索引

RangeIndex(start=0, stop=4, step=1)

In [19]:
s1.values  # 所有的值， 是一个数组

array([1, 2, 3, 4], dtype=int64)

In [20]:
s2 = Series(np.random.randint(1, 100, size=(2, 4)))

Exception: Data must be 1-dimensional

### 通过 index 设置索引

- 指定索引，注意索引的个数要和值的个数是对应的

In [29]:
s2 =Series([1, 2, 3], index=['a', 'b', 'c'])

### 由字典来创建

In [23]:
s = {'a': 1, 'b': 2, 'c': 3}
ss = Series(s)

In [24]:
type(ss)

pandas.core.series.Series

In [43]:
s3 = Series([150, 140, 120, 123], index=["语文","数学","英语","综合"])

### 索引和切片

(1) 显示索引
- 使用 index 中的元素作为索引
- 使用 .loc 作为索引

In [31]:
s2

a    1
b    2
c    3
dtype: int64

In [32]:
s2.loc["a"]

1

In [34]:
s2["b"]

2

In [35]:
s2.loc[["a", "b"]]

a    1
b    2
dtype: int64

In [36]:
s2.loc[["c"]]

c    3
dtype: int64

In [37]:
s2[["b"]]

b    2
dtype: int64

### 隐式索引，获取元素

In [38]:
s2[0]

1

In [40]:
s2.iloc[[0]]  # indexlocation  通过索引号定位元素

a    1
dtype: int64

### 切片

In [44]:
s3

语文    150
数学    140
英语    120
综合    123
dtype: int64

In [45]:
s3[0:2]

语文    150
数学    140
dtype: int64

In [46]:
s3.loc["数学"]

140

In [47]:
s3["数学"]

140

In [49]:
s3[1]

140

In [50]:
s3.iloc[1]

140

### 切片
### 常用的属性和方法

shape size index values
- shape 是一个一维的数组
- size 元素的个数
- index  索引
- values 值

In [52]:
s1.shape

(4,)

### head()  tail()

- head()  取前面几个值  默认值是 5
- tail() 取后面的几个值  默认是5

In [54]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [55]:
s1.head()
s1.tail()

0    1
1    2
2    3
3    4
dtype: int64

### 多维数组如果有 None 和 nan 就无法进行求和

#### Series 中的 会忽略 None 和 nan 进行求和

- isnull() 内部元素是 nan 则返回 True 
- notnull()  不是 nan 返回 True

In [69]:
n1 = np.array([1, 2, 3, 4, 45, np.nan, None])


In [70]:
s3 = Series([1, 2, 3, 4, 45, np.nan, None])

In [71]:
s3.sum()

55.0

In [72]:
s3

0     1.0
1     2.0
2     3.0
3     4.0
4    45.0
5     NaN
6     NaN
dtype: float64

In [73]:
s3.isnull()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

### 对数据进行清洗， 剔除空值


In [75]:
s3

0     1.0
1     2.0
2     3.0
3     4.0
4    45.0
5     NaN
6     NaN
dtype: float64

In [77]:
condition = s3.isnull()

In [82]:
s3[condition] = 0

In [83]:
s3

0     1.0
1     2.0
2     3.0
3     4.0
4    45.0
5     0.0
6     0.0
dtype: float64

### name 属性

In [89]:
s3 = Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"], name="a")

In [90]:
s4 = Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"], name="b")

In [91]:
s3

a    1
b    2
c    3
d    4
e    5
Name: a, dtype: int64

In [92]:
s4

a    1
b    2
c    3
d    4
e    5
Name: b, dtype: int64

In [93]:
s4 + 50

a    51
b    52
c    53
d    54
e    55
Name: b, dtype: int64

In [94]:
s4 * 2

a     2
b     4
c     6
d     8
e    10
Name: b, dtype: int64

### 运算

- 是根据对应的索引来查找对应的位置进行运算

In [96]:
s4 + s3

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [97]:
s3

a    1
b    2
c    3
d    4
e    5
Name: a, dtype: int64

In [98]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [99]:
s1 + s3

0   NaN
1   NaN
2   NaN
3   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [101]:
s1.add(s3, fill_value=0)

0    1.0
1    2.0
2    3.0
3    4.0
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

### 作业

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series, DataFrame

In [7]:
ndarray1 = np.zeros(shape=10)
ndarray1[4] = 1
ndarray1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [10]:
ndarray2 = np.arange(10, 50)
ndarray2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [20]:
ndarray4 = np.random.random(size=(10, 10))
np.max(ndarray4)
np.min(ndarray4)
ndarray5 = np.zeros(shape=(10, 10))
ndarray5[[0, -1]] = 1
ndarray5[:,[0, -1]] = 1

ndarray5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
nd = np.random.randint(1, 100, size=(5, 5))

nd

array([[78, 86, 89, 79, 90],
       [90,  6,  3, 99, 44],
       [78, 84, 92, 54, 30],
       [57, 48, 48, 92, 19],
       [96,  6, 42, 98,  9]])

In [24]:
nd[[0, -1]]

array([[78, 86, 89, 79, 90],
       [96,  6, 42, 98,  9]])

In [23]:
nd[[0, -1], [0, -1]]

array([78,  9])

In [29]:
nd[[0, -1], [0, -1]]

array([78,  9])

In [33]:
n1 = np.zeros(shape=5)
n2 = np.arange(5)
n1 + n2.reshape(5, 1)

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [36]:
np.full(shape=(5, 5), fill_value=(0,1,2,3,4))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [42]:
ndarray8 = np.random.randint(0, 100, 10)
ndarray8

array([65, 88, 48, 31, 33, 80, 71, 71, 34, 14])

In [40]:
np.sort(ndarray8)

array([ 1,  2, 13, 23, 26, 32, 40, 44, 56, 71])

In [46]:
index = np.argmax(ndarray8)
index

1

In [48]:
ndarray8[index] = 0
ndarray8

array([65,  0, 48, 31, 33, 80, 71, 71, 34, 14])

In [49]:
ndarray10 = np.random.randint(0, 100, size=(5, 5))
ndarray10

array([[82, 11, 57, 26,  4],
       [68, 42,  1, 12, 46],
       [90, 71, 18, 62, 88],
       [72, 47, 15, 25, 66],
       [47, 92, 33, 61, 59]])

In [54]:
ndarray10[:, 2]

array([57,  1, 18, 15, 33])

In [55]:
# 排序，按照数值的大小把索引返回

index2 = ndarray10[:, 2].argsort()
index

array([1, 3, 2, 4, 0], dtype=int64)

In [56]:
ndarray10[index2]

array([[68, 42,  1, 12, 46],
       [72, 47, 15, 25, 66],
       [90, 71, 18, 62, 88],
       [47, 92, 33, 61, 59],
       [82, 11, 57, 26,  4]])

### DataFrame

DataFrame 是一个表格型的户数结构， 既有行索引，也有列索引

- 行索引： index
- 列索引： column
- 值： values(numpy的二维数组)

In [57]:
from pandas import DataFrame

In [84]:
df = DataFrame(data=([1, 2, 3, 4, 5]))
ndarray = np.random.randint(0, 150, size=(5, 2))
df2 = DataFrame(data=ndarray, index=list('abcde'), columns=["first", "second"])


AttributeError: module 'numpy' has no attribute 'float8'

In [85]:
df2.values

array([[ 61, 105],
       [ 80, 149],
       [117, 115],
       [131,   4],
       [ 40,  14]])

In [86]:
df2.index
df2.shape

(5, 2)

In [96]:
df2.columns
"语文 数学 英语 理综".split()
"张 里".split()

['张', '里']

In [97]:
data = np.random,randint(0, 150, size=(4, 2))
index = "语文 数学 英语 理综".split()
col = "张 里".split()
df = DataFrame(data=data, index=index， columns=col)

SyntaxError: invalid character in identifier (<ipython-input-97-f63058301405>, line 4)

### 列索引， 行切片

### 对列进行索引

- `df.columns_name ` 
- `df["columns_name"]`
- 获取的一列是一个 Series 对象

### 对行进行索引

- `df.loc["index_name"]`
- `df.iloc[index]`
- loc 方法可以传入行的名称和列的名称来定位元素， 但是必须行元素在列元素的前面

### 终极方法
- `df.values[0, 0]`
- df.values 得到的是一个数组，通过索引操作获取对应的元素

### 切片
- `df[0:2]` 获取的是行

### 列切片

- `df.iloc[:, 0:2]`
- 需要通过 iloc[]  进行对列的切片

### DataFrame 的运算

- \+ 对内部所有的values都加 对应的数值
- df["columns_name"] += 1

### DataFrame 之间做运算

- 加法：行和列都对应的 对应的元素相加
    - 不对应的位置相加为 NaN

In [103]:
df1 = DataFrame(np.random.randint(0, 150, size=(5, 4)), 
               index=list("12345"),
               columns=list("ABCD"))
df2 = DataFrame(np.random.randint(0, 150, size=(5, 5)), 
               index=list("12345"),
               columns=list("ABCDE"))

In [104]:
display(df1, df2)

A    B    C    D
1    8    0   27   27
2  117  142  112   68
3  111  103   85   17
4   34  105   65   60
5   20   44  144  106

A    B    C    D   E
1   48  137    9   20  51
2   53  111  126   19   0
3  133   81   26  143  73
4   71   97   81   55  47
5   77  124   41  140  43

In [105]:
df1 + df2

A    B    C    D   E
1   56  137   36   47 NaN
2  170  253  238   87 NaN
3  244  184  111  160 NaN
4  105  202  146  115 NaN
5   97  168  185  246 NaN

### DateFrame 和 Series 运算

- 广播机制
- Series 和 DataFrame 的索引对应， 对应位置相加

- 默认 是Series的索引 和 DataFrame 的列索引("columns")进行相加
- 可以指定 来进行 index 进行就想家
- `s2.add(s1, axis="index")`

In [110]:
from pandas import DataFrame

data = np.random.randint(50, 150, size=(3, 4))
index = ["张三", "李四", "王五"]
columns = ["语文","数学", "英语","Python"]
df1 = DataFrame(data=data, index=index, columns=columns)

In [113]:
data = np.random.randint(50, 150, size=(3, 4))
index = ["张三", "李四", "王五"]
columns = ["语文","数学", "英语","Python"]
df2 = DataFrame(data=data, index=index, columns=columns)

In [115]:
display(df1, df2)

语文   数学   英语  Python
张三  107   95   93     103
李四  125   56   54      86
王五   64  110  144     141

语文  数学   英语  Python
张三   62  64   71      80
李四   51  97  114      68
王五  112  83   69     104

In [116]:
df1 + df2

语文   数学   英语  Python
张三  169  159  164     183
李四  176  153  168     154
王五  176  193  213     245

In [118]:
(df1 + df2) / 2

语文    数学     英语  Python
张三  84.5  79.5   82.0    91.5
李四  88.0  76.5   84.0    77.0
王五  88.0  96.5  106.5   122.5

In [120]:
display(df1, df2)

语文   数学   英语  Python
张三  107   95   93     103
李四  125   56   54      86
王五   64  110  144     141

语文  数学   英语  Python
张三   62  64   71      80
李四   51  97  114      68
王五  112  83   69     104

In [123]:
df1.loc["张三"].loc["数学"] = 0
df1

语文   数学   英语  Python
张三  107    0   93     103
李四  125   56   54      86
王五   64  110  144     141

In [124]:
df1.loc["李四"] += 100
df1

语文   数学   英语  Python
张三  107    0   93     103
李四  225  156  154     186
王五   64  110  144     141

In [125]:
df1 += 10
df1 

语文   数学   英语  Python
张三  117   10  103     113
李四  235  166  164     196
王五   74  120  154     151

In [132]:
dates = pd.date_range(start="20130101", end="20130202")
dates

DatetimeIndex(['2013-01-01 00:00:00', '2013-01-06 08:00:00',
               '2013-01-11 16:00:00', '2013-01-17 00:00:00',
               '2013-01-22 08:00:00', '2013-01-27 16:00:00',
               '2013-02-02 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [135]:
dates = pd.date_range("20130101", periods=6) # periods 取几个
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [136]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("abcd"))

In [137]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-04 -0.190139  0.830868  2.148413 -0.182896
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [138]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-04 -0.190139  0.830868  2.148413 -0.182896
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [139]:
df.values

array([[ 2.17625451e+00,  2.95262433e-01,  2.28860279e-01,
         2.26367207e+00],
       [ 1.75313800e-01, -8.89545369e-01, -7.38617573e-04,
         1.21630512e+00],
       [ 7.90816162e-01, -8.38169090e-01, -2.37055856e+00,
         5.92835555e-01],
       [-1.90138989e-01,  8.30867670e-01,  2.14841341e+00,
        -1.82896449e-01],
       [ 6.05591194e-01, -8.78522094e-01, -4.63230848e-01,
        -1.44436880e+00],
       [-2.01424133e-01, -1.32097000e+00,  6.79868484e-01,
         6.36110663e-01]])

In [140]:
df.describe()

a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean   0.559402 -0.466846  0.037102  0.513610
std    0.889729  0.834318  1.480280  1.256709
min   -0.201424 -1.320970 -2.370559 -1.444369
25%   -0.098776 -0.886790 -0.347608  0.011037
50%    0.390452 -0.858346  0.114061  0.614473
75%    0.744510  0.011905  0.567116  1.071257
max    2.176255  0.830868  2.148413  2.263672

In [142]:
display(df, df.T)

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-04 -0.190139  0.830868  2.148413 -0.182896
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

2013-01-01  2013-01-02     ...      2013-01-05  2013-01-06
a    2.176255    0.175314     ...        0.605591   -0.201424
b    0.295262   -0.889545     ...       -0.878522   -1.320970
c    0.228860   -0.000739     ...       -0.463231    0.679868
d    2.263672    1.216305     ...       -1.444369    0.636111

[4 rows x 6 columns]

In [146]:
df.sort_index(axis=1, ascending=True) # ascending False 倒序

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-04 -0.190139  0.830868  2.148413 -0.182896
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [149]:
df.sort_values(by="b")   # 按某列的值进行 小 到大排序

a         b         c         d
2013-01-06 -0.201424 -1.320970  0.679868  0.636111
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-04 -0.190139  0.830868  2.148413 -0.182896

In [150]:
df.loc[dates[0]]

a    2.176255
b    0.295262
c    0.228860
d    2.263672
Name: 2013-01-01 00:00:00, dtype: float64

In [153]:
df.a.values

array([ 2.17625451,  0.1753138 ,  0.79081616, -0.19013899,  0.60559119,
       -0.20142413])

In [155]:
df.loc[:,["a", "b"]].values

array([[ 2.17625451,  0.29526243],
       [ 0.1753138 , -0.88954537],
       [ 0.79081616, -0.83816909],
       [-0.19013899,  0.83086767],
       [ 0.60559119, -0.87852209],
       [-0.20142413, -1.32097   ]])

In [157]:
df.loc[dates[0]:dates[2], ["a", "b"]]

a         b
2013-01-01  2.176255  0.295262
2013-01-02  0.175314 -0.889545
2013-01-03  0.790816 -0.838169

In [160]:
df.loc[dates[0], ["a", "b"]]

a    2.176255
b    0.295262
Name: 2013-01-01 00:00:00, dtype: float64

In [163]:
df.at[dates[0], "a"]

2.176254511689243

## 处理数据丢失

- None: Pyhton 自带的数据类型，不能参与到任何的计算中, 直接报异常
- np.nan(NaN) : float类型， 能参与计算， 但结果是 NaN

In [165]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

### np.nan(NaN)

- 数组直接运算会得到 nan
- 使用 `np.nan*()` 会将nan 当做 0 处理
- Series 和 DataFrame 默认将 nan 当做 0 处理

In [178]:
ndarray1 = np.array([1, 2, 3 ,4, np.nan])
ndarray1

array([ 1.,  2.,  3.,  4., nan])

In [179]:
np.sum(ndarray1)

nan

In [180]:
np.nansum(ndarray1)

10.0

In [181]:
s1 = Series([1, 2, 3, np.nan])
s1.sum()

6.0

In [182]:
# 将 nan 
df1 = DataFrame([1, 2, 3, np.nan])
df1.sum()

0    6.0
dtype: float64

### pandas 中 的None 和 np.nan

- pandas 中的 None 和 np.nan 都视为 NaN

In [183]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -2.370559  0.592836
2013-01-04 -0.190139  0.830868  2.148413 -0.182896
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [192]:
df.iloc[2].loc["c"] = None
df.iloc[3].loc["a"] = np.nan
df["d"].iloc[3] = None
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN  0.830868  2.148413       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [196]:
df.isnull()  # NaN 返回的是 True

a      b      c      d
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03  False  False   True  False
2013-01-04   True  False  False   True
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

In [198]:
df.notnull()  # 不是空值返回True

a     b      c      d
2013-01-01   True  True   True   True
2013-01-02   True  True   True   True
2013-01-03   True  True  False   True
2013-01-04  False  True   True  False
2013-01-05   True  True   True   True
2013-01-06   True  True   True   True

In [202]:
df.isnull()

a      b      c      d
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03  False  False   True  False
2013-01-04   True  False  False   True
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

In [203]:
df.isnull().any() # 只要有 True 就是True 

a     True
b    False
c     True
d     True
dtype: bool

In [205]:
df.isnull().any(axis=1)

2013-01-01    False
2013-01-02    False
2013-01-03     True
2013-01-04     True
2013-01-05    False
2013-01-06    False
Freq: D, dtype: bool

### dropna() 

- 将有空值的 行进行删除  默认的 axis 是 0， 改为 1 会对列进行处理
- how 表示怎么处理， 默认是 any 有一个空的就删除
- all 全部是空的才删除


In [212]:
df.dropna()
df.dropna(axis=0, how="all")

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN  0.830868  2.148413       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [214]:
df["b"].iloc[3] = None
df["c"].iloc[3] = None

In [217]:
df.dropna(axis=0, how="all")

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

### 空值填充 fillna()

- 遇到空值设置为我们指定的值 value = 
- 在 空值 所处的位置的 前后找值进行填充 method="bfill" / "pad" "fill"

In [219]:
df.fillna(value=0)

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169  0.000000  0.592836
2013-01-04  0.000000  0.000000  0.000000  0.000000
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [221]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [222]:
df.fillna(method="bfill")  # 默认是在 columns 中前后进行查找填充

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -0.463231  0.592836
2013-01-04  0.605591 -0.878522 -0.463231 -1.444369
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [225]:
df.fillna(method="ffill", axis=1)  # axis 是1 是 是按照 index 进行查找

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169 -0.838169  0.592836
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [226]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970  0.679868  0.636111

In [227]:
df["c"].iloc[5] = np.nan

In [228]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970       NaN  0.636111

In [232]:
df.fillna(method="bfill", limit=1) # limit 限制 向前查找几次

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04  0.605591 -0.878522 -0.463231 -1.444369
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970       NaN  0.636111

In [233]:
df

a         b         c         d
2013-01-01  2.176255  0.295262  0.228860  2.263672
2013-01-02  0.175314 -0.889545 -0.000739  1.216305
2013-01-03  0.790816 -0.838169       NaN  0.592836
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970       NaN  0.636111

In [235]:
df.iloc[3:5, 1:2]

b
2013-01-04       NaN
2013-01-05 -0.878522

In [236]:
df.iloc[3]

a   NaN
b   NaN
c   NaN
d   NaN
Name: 2013-01-04 00:00:00, dtype: float64

In [237]:
df.iloc[[1, 2, 3], [0, 2]]

a         c
2013-01-02  0.175314 -0.000739
2013-01-03  0.790816       NaN
2013-01-04       NaN       NaN

In [238]:
df.iloc[:, 1:3]

b         c
2013-01-01  0.295262  0.228860
2013-01-02 -0.889545 -0.000739
2013-01-03 -0.838169       NaN
2013-01-04       NaN       NaN
2013-01-05 -0.878522 -0.463231
2013-01-06 -1.320970       NaN

In [239]:
df.iloc[1,1]

-0.8895453692451164

In [243]:
df.iat[1, 1] # iat 和 iloc 用法相同，但功能没有 iloc 强大

-0.8895453692451164

In [249]:
df[df < 0]

a         b         c         d
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02       NaN -0.889545 -0.000739       NaN
2013-01-03       NaN -0.838169       NaN       NaN
2013-01-04       NaN       NaN       NaN       NaN
2013-01-05       NaN -0.878522 -0.463231 -1.444369
2013-01-06 -0.201424 -1.320970       NaN       NaN

In [250]:
df2 = df.copy()


In [251]:
df2["E"] = ["one","two","three","four","five","six"]

In [252]:
df2

a         b         c         d      E
2013-01-01  2.176255  0.295262  0.228860  2.263672    one
2013-01-02  0.175314 -0.889545 -0.000739  1.216305    two
2013-01-03  0.790816 -0.838169       NaN  0.592836  three
2013-01-04       NaN       NaN       NaN       NaN   four
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369   five
2013-01-06 -0.201424 -1.320970       NaN  0.636111    six

In [253]:
df2[df2["E"].isin(["two", "four"])]

a         b         c         d     E
2013-01-02  0.175314 -0.889545 -0.000739  1.216305   two
2013-01-04       NaN       NaN       NaN       NaN  four

### 多级的索引

- 隐式的构造， 给DataFrame 构造韩式的 index 参数传递两个或者更多的数组

- Series 也可以创建多层索引

In [254]:
index = [np.array(["期中","期中","期末","期末"]),np.array(["语文","数学","语文","数学"])]

Series(np.random.randn(4), index=index)

期中  语文   -0.432269
    数学   -0.105683
期末  语文   -1.163431
    数学    0.640759
dtype: float64

### 显示的创建多层索引

- 使用数组

In [258]:
index = pd.MultiIndex.from_arrays(["期中","期中","期中","期末","期末","期末"], 
                                  ["语文","数学","英语","语文","数学","英语"])
columns = ["张三","李四","王五","赵六"]

data = np.random.randint(50, 150, size=(6, 4))

DataFrame(data, index=index, columns=columns)



TypeError: Input must be list-like

In [270]:
index = pd.MultiIndex.from_product([["期中","期末"],
                                   ["语文","数学","英语"]])
columns = ["张三","李四","王五","赵六"]

data = np.random.randint(50, 150, size=(6, 4))

df2 = DataFrame(data=data, index=index, columns=columns)


In [271]:
data = np.random.randint(50, 120, size=(4,2))
index = pd.MultiIndex.from_product([["期中","期末"], 
                                   ["语文","数学"]])
columns = ["张三", "李四"]
DataFrame(data, index, columns)

张三  李四
期中 语文   99  54
   数学   76  59
期末 语文  103  84
   数学   99  50

### 多层列索引

- 和 行 索引相同的方法可以构建

In [272]:
data = np.random.randint(50, 120, size=(2, 4))
index = pd.MultiIndex.from_product([["期中","期末"], 
                                   ["语文","数学"]])
columns = ["张三", "李四"]
DataFrame(data=data, columns=index, index=columns)

期中      期末     
     语文  数学  语文   数学
张三  102  52  81   55
李四   88  88  59  118

### 多层索引 查找数据， 切片

In [273]:
df2

张三   李四   王五   赵六
期中 语文   86   55   67  137
   数学  137  101  104   64
   英语  125   85  113  109
期末 语文   69  114  120  116
   数学  129   51   55   86
   英语   50   66  135   90

In [277]:
df2["张三"]   # 得到一个由多重索引的 Series

期中  语文     86
    数学    137
    英语    125
期末  语文     69
    数学    129
    英语     50
Name: 张三, dtype: int32

In [279]:
df2["张三"].loc["期中"].loc["语文"]

86

In [282]:
df2.iloc[5]

张三     50
李四     66
王五    135
赵六     90
Name: (期末, 英语), dtype: int32

In [285]:
df2.loc["期中"].loc["语文"]

张三     86
李四     55
王五     67
赵六    137
Name: 语文, dtype: int32

In [289]:
df2[0:3]

张三   李四   王五   赵六
期中 语文   86   55   67  137
   数学  137  101  104   64
   英语  125   85  113  109

In [290]:
df2.iloc[1:3, :3]

张三   李四   王五
期中 数学  137  101  104
   英语  125   85  113

In [295]:
data = np.random.randint(50, 120, size=(6, 12))
index = pd.MultiIndex.from_product([["期中","期末"], 
                                   ["语文","数学","英语"]])
columns = pd.MultiIndex.from_product([["一班","二班"],
                                      ["01","02","03","04","05","06"]])
df1 = DataFrame(data=data, columns=columns, index=index)

In [296]:
df1

一班                           二班                         
        01  02   03   04   05   06   01   02   03   04   05   06
期中 语文   70  96   92  101   73   75   64   90   58   69   75   57
   数学   61  99  102   78   62   69   89   84   89   61   74   86
   英语  119  66  103   86  102  108   86   97  102   86  103   69
期末 语文   79  67   98   77   61  116   74  119  116   86  109  115
   数学  119  62   58   85  107  112  108   62   68   64  111  103
   英语   71  84   57  110  113   57   60  116  107  108   73   66

### 切片

In [301]:
df1.iloc[0:5, 2:5]

一班          
        03   04   05
期中 语文   92  101   73
   数学  102   78   62
   英语  103   86  102
期末 语文   98   77   61
   数学   58   85  107

In [302]:
df1["一班"]["03"]

期中  语文     92
    数学    102
    英语    103
期末  语文     98
    数学     58
    英语     57
Name: 03, dtype: int32

In [303]:
df1.loc["期中"]

一班                          二班                      
     01  02   03   04   05   06  01  02   03  04   05  06
语文   70  96   92  101   73   75  64  90   58  69   75  57
数学   61  99  102   78   62   69  89  84   89  61   74  86
英语  119  66  103   86  102  108  86  97  102  86  103  69

In [305]:
df1.loc["期中"].loc["数学"]

一班  01     61
    02     99
    03    102
    04     78
    05     62
    06     69
二班  01     89
    02     84
    03     89
    04     61
    05     74
    06     86
Name: 数学, dtype: int32

In [307]:
df1.loc["期中"][0:2]

一班                        二班                    
    01  02   03   04  05  06  01  02  03  04  05  06
语文  70  96   92  101  73  75  64  90  58  69  75  57
数学  61  99  102   78  62  69  89  84  89  61  74  86

In [314]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], 
               index=pd.date_range("20130101", periods=6))
s1

2013-01-01    1
2013-01-02    2
2013-01-03    3
2013-01-04    4
2013-01-05    5
2013-01-06    6
Freq: D, dtype: int64

In [315]:
df

a         b         c         d   F
2013-01-01  2.176255  0.295262  0.228860  2.263672 NaN
2013-01-02  0.175314 -0.889545 -0.000739  1.216305 NaN
2013-01-03  0.790816 -0.838169       NaN  0.592836 NaN
2013-01-04       NaN       NaN       NaN       NaN NaN
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369 NaN
2013-01-06 -0.201424 -1.320970       NaN  0.636111 NaN

In [316]:
df["F"] = s1
df

a         b         c         d  F
2013-01-01  2.176255  0.295262  0.228860  2.263672  1
2013-01-02  0.175314 -0.889545 -0.000739  1.216305  2
2013-01-03  0.790816 -0.838169       NaN  0.592836  3
2013-01-04       NaN       NaN       NaN       NaN  4
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369  5
2013-01-06 -0.201424 -1.320970       NaN  0.636111  6

In [317]:
df.at[dates[0], "a"] = 0

In [318]:
df

a         b         c         d  F
2013-01-01  0.000000  0.295262  0.228860  2.263672  1
2013-01-02  0.175314 -0.889545 -0.000739  1.216305  2
2013-01-03  0.790816 -0.838169       NaN  0.592836  3
2013-01-04       NaN       NaN       NaN       NaN  4
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369  5
2013-01-06 -0.201424 -1.320970       NaN  0.636111  6

In [319]:
df.iat[0, 1] = 0
df

a         b         c         d  F
2013-01-01  0.000000  0.000000  0.228860  2.263672  1
2013-01-02  0.175314 -0.889545 -0.000739  1.216305  2
2013-01-03  0.790816 -0.838169       NaN  0.592836  3
2013-01-04       NaN       NaN       NaN       NaN  4
2013-01-05  0.605591 -0.878522 -0.463231 -1.444369  5
2013-01-06 -0.201424 -1.320970       NaN  0.636111  6

In [322]:
df.loc[:, "d"] = np.array([5] * len(df))

In [323]:
df

a         b         c  d  F
2013-01-01  0.000000  0.000000  0.228860  5  1
2013-01-02  0.175314 -0.889545 -0.000739  5  2
2013-01-03  0.790816 -0.838169       NaN  5  3
2013-01-04       NaN       NaN       NaN  5  4
2013-01-05  0.605591 -0.878522 -0.463231  5  5
2013-01-06 -0.201424 -1.320970       NaN  5  6

In [325]:
[5, 4] * 5

[5, 4, 5, 4, 5, 4, 5, 4, 5, 4]

In [326]:
df

a         b         c  d  F
2013-01-01  0.000000  0.000000  0.228860  5  1
2013-01-02  0.175314 -0.889545 -0.000739  5  2
2013-01-03  0.790816 -0.838169       NaN  5  3
2013-01-04       NaN       NaN       NaN  5  4
2013-01-05  0.605591 -0.878522 -0.463231  5  5
2013-01-06 -0.201424 -1.320970       NaN  5  6

In [327]:
df2 = df.copy()
df2[df2 > 2] = -df2

In [328]:
df2

a         b         c  d  F
2013-01-01  0.000000  0.000000  0.228860 -5  1
2013-01-02  0.175314 -0.889545 -0.000739 -5  2
2013-01-03  0.790816 -0.838169       NaN -5 -3
2013-01-04       NaN       NaN       NaN -5 -4
2013-01-05  0.605591 -0.878522 -0.463231 -5 -5
2013-01-06 -0.201424 -1.320970       NaN -5 -6

In [329]:
df

a         b         c  d  F
2013-01-01  0.000000  0.000000  0.228860  5  1
2013-01-02  0.175314 -0.889545 -0.000739  5  2
2013-01-03  0.790816 -0.838169       NaN  5  3
2013-01-04       NaN       NaN       NaN  5  4
2013-01-05  0.605591 -0.878522 -0.463231  5  5
2013-01-06 -0.201424 -1.320970       NaN  5  6

In [332]:
df3 = df.copy()
df3[df3.isnull()] = 100
df3

a           b           c  d  F
2013-01-01    0.000000    0.000000    0.228860  5  1
2013-01-02    0.175314   -0.889545   -0.000739  5  2
2013-01-03    0.790816   -0.838169  100.000000  5  3
2013-01-04  100.000000  100.000000  100.000000  5  4
2013-01-05    0.605591   -0.878522   -0.463231  5  5
2013-01-06   -0.201424   -1.320970  100.000000  5  6

In [333]:
-df2

a         b         c    d    F
2013-01-01 -0.000000 -0.000000 -0.228860  5.0 -1.0
2013-01-02 -0.175314  0.889545  0.000739  5.0 -2.0
2013-01-03 -0.790816  0.838169       NaN  5.0  3.0
2013-01-04       NaN       NaN       NaN  5.0  4.0
2013-01-05 -0.605591  0.878522  0.463231  5.0  5.0
2013-01-06  0.201424  1.320970       NaN  5.0  6.0

### 缺失值处理

- reindex() 将制定的轴上的索引进行改变，增加， 删除，返回原始数据的拷贝

In [337]:
df1 = df.reindex(index=dates[0:4], 
                 columns=list(df.columns) + ["E"])
df1.loc[dates[0]:dates[1], "E"] = 1
df1

a         b         c  d  F    E
2013-01-01  0.000000  0.000000  0.228860  5  1  1.0
2013-01-02  0.175314 -0.889545 -0.000739  5  2  1.0
2013-01-03  0.790816 -0.838169       NaN  5  3  NaN
2013-01-04       NaN       NaN       NaN  5  4  NaN

In [342]:
df1.dropna(how="any")

a         b         c  d  F    E
2013-01-01  0.000000  0.000000  0.228860  5  1  1.0
2013-01-02  0.175314 -0.889545 -0.000739  5  2  1.0

In [344]:
df1.fillna(value=5)

a         b         c  d  F    E
2013-01-01  0.000000  0.000000  0.228860  5  1  1.0
2013-01-02  0.175314 -0.889545 -0.000739  5  2  1.0
2013-01-03  0.790816 -0.838169  5.000000  5  3  5.0
2013-01-04  5.000000  5.000000  5.000000  5  4  5.0

In [348]:
pd1 = pd.isnull(df1)

In [350]:
pd2 = df1.isnull()
display(type(pd1), type(pd2))

pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

### 相关操作， 聚合函数

In [351]:
df

a         b         c  d  F
2013-01-01  0.000000  0.000000  0.228860  5  1
2013-01-02  0.175314 -0.889545 -0.000739  5  2
2013-01-03  0.790816 -0.838169       NaN  5  3
2013-01-04       NaN       NaN       NaN  5  4
2013-01-05  0.605591 -0.878522 -0.463231  5  5
2013-01-06 -0.201424 -1.320970       NaN  5  6

In [355]:
df.mean()

a    0.274059
b   -0.785441
c   -0.078370
d    5.000000
F    3.500000
dtype: float64

### 对于拥有不同的维度，需要对其的对象进行操作， Pandas 会自动沿着制定的维度进行广播：

In [359]:
s = pd.Series([1, 2, 3, 4, np.nan, 7],
             index=dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    2.0
2013-01-05    3.0
2013-01-06    4.0
Freq: D, dtype: float64

In [ ]:
df.sub(s, axis="index")

In [364]:
df.apply(np.cumsum)

a         b         c   d   F
2013-01-01  0.000000  0.000000  0.228860   5   1
2013-01-02  0.175314 -0.889545  0.228122  10   3
2013-01-03  0.966130 -1.727714       NaN  15   6
2013-01-04       NaN       NaN       NaN  20  10
2013-01-05  1.571721 -2.606237 -0.235109  25  15
2013-01-06  1.370297 -3.927207       NaN  30  21

In [368]:
df.apply(lambda x: x.max() - x.min(), axis=1)

2013-01-01    5.000000
2013-01-02    5.889545
2013-01-03    5.838169
2013-01-04    1.000000
2013-01-05    5.878522
2013-01-06    7.320970
Freq: D, dtype: float64

In [369]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    5
1    2
2    3
3    5
4    3
5    3
6    5
7    3
8    1
9    5
dtype: int32

In [371]:
s.value_counts()

5    4
3    4
2    1
1    1
dtype: int64

In [372]:
s = pd.Series(["a", "b", "c","sda", np.nan, "sdfsd", "cat"])

In [373]:
s

0        a
1        b
2        c
3      sda
4      NaN
5    sdfsd
6      cat
dtype: object

In [376]:
s.str.title()

0        A
1        B
2        C
3      Sda
4      NaN
5    Sdfsd
6      Cat
dtype: object

### 合并

- pandas 可以轻松的对 Series DataFrame 和 Panel 对象进行各种符合逻辑关系的合并操作

#### Concat

In [377]:
df = pd.DataFrame(np.random.randn(10, 4))
df

0         1         2         3
0 -1.108339  1.964120  0.110565  0.633353
1 -2.060931 -1.735060 -0.517987  0.694184
2  2.054525  1.170012  1.265432  1.337392
3  0.162554  1.744949 -1.362536  1.373669
4 -0.743903 -1.119013 -0.202580 -3.030877
5 -0.360038  0.103380 -1.507692 -0.385569
6 -0.507372 -1.220851 -0.159463 -1.050578
7 -0.517781  0.543914  1.267544 -1.806071
8  0.108944  0.123512  0.524884 -0.297674
9 -0.328183  0.623364 -0.550351  1.708048

In [378]:
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0 -1.108339  1.964120  0.110565  0.633353
 1 -2.060931 -1.735060 -0.517987  0.694184
 2  2.054525  1.170012  1.265432  1.337392,
           0         1         2         3
 3  0.162554  1.744949 -1.362536  1.373669
 4 -0.743903 -1.119013 -0.202580 -3.030877
 5 -0.360038  0.103380 -1.507692 -0.385569
 6 -0.507372 -1.220851 -0.159463 -1.050578,
           0         1         2         3
 7 -0.517781  0.543914  1.267544 -1.806071
 8  0.108944  0.123512  0.524884 -0.297674
 9 -0.328183  0.623364 -0.550351  1.708048]

In [380]:
pd.concat(pieces)

0         1         2         3
0 -1.108339  1.964120  0.110565  0.633353
1 -2.060931 -1.735060 -0.517987  0.694184
2  2.054525  1.170012  1.265432  1.337392
3  0.162554  1.744949 -1.362536  1.373669
4 -0.743903 -1.119013 -0.202580 -3.030877
5 -0.360038  0.103380 -1.507692 -0.385569
6 -0.507372 -1.220851 -0.159463 -1.050578
7 -0.517781  0.543914  1.267544 -1.806071
8  0.108944  0.123512  0.524884 -0.297674
9 -0.328183  0.623364 -0.550351  1.708048

### Join

    - 类似于 SQL 的合并

In [381]:
left = pd.DataFrame({"keys":["foo", "foo"],
                    "lval":[1, 2]})
right = pd.DataFrame({"keys":["foo", "foo"],
                     "rval":[4, 5]})
left

keys  lval
0  foo     1
1  foo     2

In [382]:
right

keys  rval
0  foo     4
1  foo     5

In [384]:
pd.merge(left, right, on="keys")

keys  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [391]:
data = np.random.randint(80, 140, size=(2, 3))
index = ["张三", "李四"]
columns = ["语文", "数学", "外语"]
df0 = DataFrame(data, index, columns)

In [392]:
df0["外语"].loc["张三"] = None
df0

语文   数学    外语
张三  100  110   NaN
李四  134  137  81.0

In [395]:
df0.fillna(method="ffill", axis=1)

语文     数学     外语
张三  100.0  110.0  110.0
李四  134.0  137.0   81.0

In [397]:
df0.fillna(method="bfill")

语文   数学    外语
张三  100  110  81.0
李四  134  137  81.0

In [401]:
data = np.random.randint(30, 120, size=(2, 6))
index = ["张三", "李四"]
columns = pd.MultiIndex.from_product([["模拟", "期中"],
                                     ["语文","数学","英语"]])
df0 = DataFrame(data, index, columns)

In [402]:
df0

模拟           期中          
     语文  数学  英语   语文   数学   英语
张三   70  30  85   86  116   40
李四  111  81  37  117  119  110

In [406]:
df0["模拟"]["英语"].loc["张三"] = None

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [410]:
df0.values[0, 2] = 0

In [412]:
df0

模拟           期中          
     语文  数学  英语   语文   数学   英语
张三   70  30   0   86  116   40
李四  111  81  37  117  119  110

In [416]:
left = pd.DataFrame({"key": ["foo", "1"],
                    "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "1"],
                    "rval": [4, 5]})

pd.merge(left, right, on="key")

key  lval  rval
0  foo     1     4
1    1     2     5

In [417]:
df = pd.DataFrame(np.random.randn(8,4), 
                  columns=["A","B","C","D"])
df

A         B         C         D
0  1.805980 -1.406750 -1.116615 -1.612881
1 -0.265512  0.873320  1.540113  0.583066
2  0.157567  0.476449 -0.353755  0.567090
3  0.519037  0.973479  0.129997 -1.025112
4 -0.156517  0.804415  1.153167 -1.077225
5 -1.289797 -1.090006 -0.662699  0.368033
6 -0.239931  0.210564  2.940967  2.478916
7  0.927177  1.238324 -1.556554  0.059778

In [419]:
s = df.iloc[3]
s

A    0.519037
B    0.973479
C    0.129997
D   -1.025112
Name: 3, dtype: float64

In [420]:
df.append(s, ignore_index=True)

A         B         C         D
0  1.805980 -1.406750 -1.116615 -1.612881
1 -0.265512  0.873320  1.540113  0.583066
2  0.157567  0.476449 -0.353755  0.567090
3  0.519037  0.973479  0.129997 -1.025112
4 -0.156517  0.804415  1.153167 -1.077225
5 -1.289797 -1.090006 -0.662699  0.368033
6 -0.239931  0.210564  2.940967  2.478916
7  0.927177  1.238324 -1.556554  0.059778
8  0.519037  0.973479  0.129997 -1.025112

### 分组

In [425]:
df = pd.DataFrame({"A":["FOO", "BAR"] * 4,
                  "B": [1, 2, 3, 4] * 2 ,
                  "C": np.random.randint(1, 9),
                  "D": np.random.randn(8)})
df

A  B  C         D
0  FOO  1  2 -0.095794
1  BAR  2  2 -0.814009
2  FOO  3  2  0.172038
3  BAR  4  2 -0.140049
4  FOO  1  2  0.025908
5  BAR  2  2 -0.959832
6  FOO  3  2  1.584657
7  BAR  4  2  0.476245

In [426]:
df.groupby("A").sum()

B  C         D
A                   
BAR  12  8 -1.437645
FOO   8  8  1.686809

In [429]:
df.groupby(["A", "B"]).sum()

C         D
A   B             
BAR 2  4 -1.773841
    4  4  0.336196
FOO 1  4 -0.069886
    3  4  1.756695

###  改变形状  Stack


In [430]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz', 
                    ['one', 'two', 'one', 'two',
 'one', 'two', 'one', 'two']]))
                    
                    

SyntaxError: invalid syntax (<ipython-input-430-82ad0357a5d0>, line 3)

In [431]:
pd.date_range()

ValueError: Of the four parameters: start, end, periods, and freq, exactly three must be specified