### Numpy 基础

In [2]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
a = np.arange(15).shape
print(a)

(15,)


In [13]:
a = np.arange(15).reshape(3,5)
a.shape

(3, 5)

In [15]:
a.ndim

2

In [18]:
a.dtype.name

'int32'

In [16]:
a.itemsize

4

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
type(a)

numpy.ndarray

In [22]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [23]:
b.shape

(3,)

In [24]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.shape

(2, 3)

In [26]:
b = np.array([1.2, 3.5, 3])
b

array([1.2, 3.5, 3. ])

In [27]:
b.dtype

dtype('float64')

In [28]:
b.itemsize

8

In [29]:
b.shape

(3,)

In [30]:
b.reshape(3, 1)

array([[1.2],
       [3.5],
       [3. ]])

In [31]:
b.ndim

1

In [32]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
a = np.ones([3, 4])
a.dtype

dtype('float64')

In [4]:
a = np.empty((3, 4))
a

array([[1.48569332e-312, 0.00000000e+000, 8.76794447e+252,
        2.15895723e+227],
       [6.48224638e+170, 3.67145870e+228, 4.51671641e-144,
        6.06003395e+233],
       [1.06400250e+248, 2.26822459e+161, 2.89847616e+131,
        1.58560488e-319]])

In [38]:

a = np.empty((3, 4))
a.dtype

dtype('float64')

In [42]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [48]:
np.zeros_like([[1,2], [3, 4]])

array([[0, 0],
       [0, 0]])

In [60]:
np.random.rand(2, 3)

array([[0.64340329, 0.60924958, 0.29339734],
       [0.17694344, 0.8985207 , 0.24687836]])

In [57]:
np.random.randn(2, 3)

array([[ 0.43855825, -0.09468512, -0.86228459],
       [ 1.20318696,  0.24234007,  1.14584436]])

In [3]:
import numpy as np
np.empty((2,3))

array([[2.67276450e+185, 1.69506143e+190, 1.75184137e+190],
       [9.48819320e+077, 1.63730399e-306, 2.22254656e-308]])

In [10]:
a = np.arange(1, 90, 5)
a.reshape(3, 6)

array([[ 1,  6, 11, 16, 21, 26],
       [31, 36, 41, 46, 51, 56],
       [61, 66, 71, 76, 81, 86]])

In [14]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [19]:
a - b
b.dtype

dtype('int32')

In [17]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

In [18]:
a.dtype

dtype('int32')

In [20]:
10 * np.sin(a) 

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [21]:
a < 35

array([ True,  True,  True, False])

In [1]:
import numpy as np

In [10]:
a = np.linspace(2, 10, 10).reshape(2, 5)
a.reshape(1, 10)

array([[ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
         6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ]])

In [12]:
np.linspace(0, np.pi, 4)

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [13]:
np.ones(3, dtype=np.int32)

array([1, 1, 1])

In [15]:
a = np.ones(3)
a.dtype

dtype('float64')

In [16]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype.name

'float64'

In [18]:
b.dtype
c = a + b

In [25]:

d = np.exp(c * 2j)
d

array([-0.41614684+0.90929743j,  0.41614684-0.90929743j,
       -0.41614684+0.90929743j])

In [26]:
np.exp(c * 1j)

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [27]:
d.dtype

dtype('complex128')

In [28]:
a = np.random.random((2, 3))

In [29]:
a

array([[0.71325381, 0.51958558, 0.6005531 ],
       [0.72455001, 0.03258345, 0.16122816]])

In [30]:
a.max()

0.724550006168714

In [31]:
a.sum()

2.7517541053785584

In [32]:
a.min()

0.032583452552515824

In [34]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
b.sum()

66

In [40]:
b.sum(axis=1)

array([ 6, 22, 38])

In [41]:
b.min(axis=1)

array([0, 4, 8])

In [44]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
b.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]], dtype=int32)

In [49]:
b.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12]], dtype=int32)

In [50]:
arr = np.arange(12).reshape(2,2,3)

In [51]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [76]:
arr[:, :, 0]

array([[0, 3],
       [6, 9]])

In [81]:
b = np.arange(3)
c = np.exp(b)
c.dtype
c

array([1.        , 2.71828183, 7.3890561 ])

In [82]:
b.dtype
b

array([0, 1, 2])

In [80]:
np.add(b,c)

array([1.        , 3.71828183, 9.3890561 ])

In [84]:
b = np.arange(12).reshape(3, 4)
for i in b:
    print(i)
    print()

[0 1 2 3]

[4 5 6 7]

[ 8  9 10 11]

